

kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "golang-whisper-build" 
spec:
  runPolicy: "Serial" 
  source: 
    git:
      uri: "https://github.com/wianvos/whisper"
  strategy:
    dockerStrategy:
      dockerfilePath: Dockerfile
  output: 
    to:
      kind: "ImageStreamTag"
      name: "whisper:latest"
  


